# Generated by Django 4.0 on 2021-12-27 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_alter_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phoneno',
            field=models.CharField(max_length=13),
        ),
    ]
