# Generated by Django 4.0 on 2021-12-27 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_alter_employee_phoneno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accountant',
        ),
    ]
