# Generated by Django 4.0 on 2021-12-26 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_alter_deduction_dedid_alter_deduction_eid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deduction',
            name='eid',
        ),
    ]
